### ISSUE TITLE
liunux版本

### ISSUE THREAD

**Issue by sportsboys** [StephenHoo/AutoLogin#1]
大佬能拓展下linux版本吗，这样直接挂在云上，天天不用操心打卡喽

**Comment by StephenHoo** [comment]
之前一直没看到，今天更新了 Linux 上的 Firefox 版本，Linux 发行版为 Debian，我在自己的云上测试是可以的，你可以按照 readme 进行配置，如果有什么问题欢迎随时联系我

**Comment by sportsboys** [comment]
Ubuntu18.04，采用你的源码重新编译，可用，感谢
