### ISSUE TITLE
每日体温字段的placeholder属性似乎不再有效了

### ISSUE THREAD

**Issue by ch1y0q** [StephenHoo/AutoLogin#4]
可以改成其他属性

**Comment by StephenHoo** [comment]
你使用的是什么版本呢？我刚刚查看了一下 Chrome 版本并无问题啊。

**Comment by ch1y0q** [comment]
> 你使用的是什么版本呢？我刚刚查看了一下 Chrome 版本并无问题啊。

chrome 84. 早上看f12源码的时候发现placeholder的属性值是空的，改成按name属性查找就能解决。有可能是系统偶尔的抽风？

**Comment by StephenHoo** [comment]
我现在也看不了打卡界面了，等到零点之后我再看看。我这边的程序显示今早7点多是打卡成功了的，你那边程序是如何显示的呢？

**Comment by StephenHoo** [comment]
我刚刚看了一下，还是正常的啊，应该是没有问题的。

![image](https://user-images.githubusercontent.com/21151479/89803774-d8945100-db65-11ea-8599-f059bebd8a32.png)
